PRODUCTS = [
    # crops
    "maize", "corn", "cassava", "tomato", "onion",
    "plantain", "yam", "cocoyam", "groundnut", "pepper",
    "beans", "rice", "sorghum", "palm oil", "banana",
    "mango", "sweet potato", "potato", "cabbage", "carrot",
    "pineapple", "papaya", "avocado", "garlic", "ginger",
    "okra", "spinach", "lettuce", "cucumber", "pumpkin",
    "coffee", "cocoa", "cotton", "sugarcane",
    # animals
    "chicken", "goat", "sheep", "cattle", "cow",
    "pig", "horse", "donkey", "duck", "turkey",
    "rabbit", "fish", "snail", "grasscutter",
    # tools
    "hoe", "machete", "shovel", "rake", "wheelbarrow",
    "watering can", "sprayer", "pump", "tractor",
    "plough", "harvester", "irrigation pipe",
    "cutlass", "axe", "sickle", "net", "cage",
    # services
    "ploughing", "plowing", "tilling", "harvesting",
    "spraying", "irrigation", "transport", "delivery",
    "mechanic", "veterinary", "consulting", "training",
    "land clearing", "pruning", "grafting", "sowing",
    "weeding", "fencing", "installation",
]

PRODUCT_SYNONYMS = {
    "corn": "maize",
    "manioc": "cassava",
    "yuca": "cassava",
    "groundnuts": "groundnut",
    "peanut": "groundnut",
    "peanuts": "groundnut",
    "hot pepper": "pepper",
    "plantains": "plantain",
    "mangoes": "mango",
    "cocoyams": "cocoyam",
    "sweet potatoes": "sweet potato",
    "yam tuber": "yam",
    "palm oil": "palm oil",
    "red oil": "palm oil",
    "palm nut": "palm oil",
    "cows": "cattle",
    "bull": "cattle",
    "bulls": "cattle",
    "fishes": "fish",
    "chickens": "chicken",
    "goats": "goat",
    "pigs": "pig",
    "sheeps": "sheep",
    "ducks": "duck",
    "turkeys": "turkey",
    "rabbits": "rabbit",
    "hens": "chicken",
    "cockerel": "chicken",
    "rooster": "chicken",
    "shovels": "shovel",
    "machetes": "machete",
    "hoes": "hoe",
    "tractors": "tractor",
    "ploughing service": "ploughing",
    "plowing service": "plowing",
    "spraying service": "spraying",
    "transport service": "transport",
    "delivery service": "delivery",
    "land clearing service": "land clearing",
    "land preparation": "land clearing",
    "mechanical work": "mechanic",
    "vet": "veterinary",
}

# Default measurements by product type
TYPE_DEFAULT_MEASUREMENTS = {
    "crop": "kg",
    "animal": "head",
    "tool": "piece",
    "service": "task",
}

# For auto-detection of measurement from user text
MEASUREMENT_KEYWORDS = [
    "kg", "kilo", "kilos", "kilogram", "kilograms",
    "bag", "bags", "sack", "sacks",
    "gallon", "gallons",
    "liter", "liters", "litre", "litres",
    "bottle", "bottles",
    "crate", "crates",
    "carton", "cartons",
    "tin", "tins",
    "piece", "pieces",
    "head", "heads",
    "bunch", "bunches",
    "dozen", "dozens",
    "ton", "tonnes",
    "hour", "hours",
    "day", "days",
    "week", "weeks",
    "month", "months",
    "task", "tasks",
    "job", "jobs",
    "session", "sessions",
    "unit", "units",
    "pair", "pairs",
    "box", "boxes",
    "basket", "baskets",
    "bowl", "bowls",
]
